// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjhvkvnshnbnxojnandf.supabase.co";
const SUPABASE_FUNCTIONS_URL = "https://mjhvkvnshnbnxojnandf.functions.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable___jaqpjR0s2bgEMxG9gjsg_pgaezEI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  functions: {
    url: SUPABASE_FUNCTIONS_URL,
  },
  global: {
    headers: {
      'Cache-Control': 'no-cache',
    },
  }
});